/**
 * BentoPack License Gatekeeper Interface
 *
 * COPYRIGHT NOTICE & END-USER LICENSE AGREEMENT:
 * This software component is proprietary and governed by plugins/LICENSE-PLUGINS.md.
 * It defines the contract for commercial feature-gating and cryptographic token validation.
 *
 * Unauthorized modification, circumvention, or redistribution of this file or
 * derivative works is strictly prohibited and constitutes willful infringement of copyright.
 */

#ifndef IGATEKEEPER_H
#define IGATEKEEPER_H

#include "bentopackcore_export.h"
#include <QString>
#include <QByteArray>
#include <QtGlobal>

namespace BentoPack {

/**
 * @brief Abstract interface for license verification and commercial feature entitlement.
 *
 * Implements a dual-license / open-core gatekeeper model:
 * - Community Edition (Apache-2.0) uses a transparent default gatekeeper.
 * - Commercial Edition uses an entangled proprietary gatekeeper governed
 *   by plugins/LICENSE-PLUGINS.md (EULA).
 */
class BENTOPACK_CORE_EXPORT ILicenseGatekeeper
{
public:
    virtual ~ILicenseGatekeeper() = default;

    /**
     * @brief Returns true if this gatekeeper represents a verified commercial license.
     */
    virtual bool isCommercial() const = 0;

    /**
     * @brief Human-readable name of the active license tier.
     */
    virtual QString editionName() const = 0;

    /**
     * @brief Signs a cryptographic challenge nonce to prove authenticity.
     * Prevents hot-swapping or dummy mock libraries from spoofing commercial status.
     * @param nonce Cryptographically random bytes generated by BentoPackCore.
     * @return Cryptographic HMAC/signature over the nonce.
     */
    virtual QByteArray signChallenge(const QByteArray &nonce) const = 0;

    /**
     * @brief Verifies that a signed challenge matches the expected secret signature.
     */
    virtual bool verifyChallenge(const QByteArray &nonce, const QByteArray &signature) const = 0;

    /**
     * @brief Entitlement check for high-value commercial features (Payload Entanglement).
     * @param featureId Numeric identifier of the feature (e.g. ASTC/KTX2 advanced compression, tight polygons).
     * @return true if unlocked and licensed.
     */
    virtual bool isFeatureUnlocked(quint32 featureId) const = 0;
};

} // namespace BentoPack

#endif // IGATEKEEPER_H
