/**
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership.  The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License.  You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied.  See the License for the
 specific language governing permissions and limitations
 under the License.
*/

#ifndef IGATEKEEPER_H
#define IGATEKEEPER_H

#include "bentopackcore_export.h"
#include <QString>
#include <QByteArray>
#include <QtGlobal>

namespace BentoPack {

/**
 * @brief Abstract interface for license verification and commercial feature entitlement.
 *
 * Implements a dual-license / open-core gatekeeper model:
 * - Community Edition (Apache-2.0) uses a transparent default gatekeeper.
 * - Commercial Edition uses an entangled proprietary gatekeeper governed
 *   by plugins/LICENSE-PLUGINS.md (EULA).
 */
class BENTOPACK_CORE_EXPORT ILicenseGatekeeper
{
public:
    virtual ~ILicenseGatekeeper() = default;

    /**
     * @brief Returns true if this gatekeeper represents a verified commercial license.
     */
    virtual bool isCommercial() const = 0;

    /**
     * @brief Human-readable name of the active license tier.
     */
    virtual QString editionName() const = 0;

    /**
     * @brief Signs a cryptographic challenge nonce to prove authenticity.
     * Prevents hot-swapping or dummy mock libraries from spoofing commercial status.
     * @param nonce Cryptographically random bytes generated by BentoPackCore.
     * @return Cryptographic HMAC/signature over the nonce.
     */
    virtual QByteArray signChallenge(const QByteArray &nonce) const = 0;

    /**
     * @brief Verifies that a signed challenge matches the expected secret signature.
     */
    virtual bool verifyChallenge(const QByteArray &nonce, const QByteArray &signature) const = 0;

    /**
     * @brief Entitlement check for high-value commercial features (Payload Entanglement).
     * @param featureId Numeric identifier of the feature (e.g. ASTC/KTX2 advanced compression, tight polygons).
     * @return true if unlocked and licensed.
     */
    virtual bool isFeatureUnlocked(quint32 featureId) const = 0;
};

} // namespace BentoPack

#endif // IGATEKEEPER_H
