#ifndef SPRITESTUDIOCORE_EXPORT_H
#define SPRITESTUDIOCORE_EXPORT_H

#include <QtCore/qglobal.h>

#if defined(SPRITESTUDIO_STATIC)
#  define SPRITESTUDIO_CORE_EXPORT
#elif defined(SPRITESTUDIO_CORE_LIBRARY)
#  define SPRITESTUDIO_CORE_EXPORT Q_DECL_EXPORT
#else
#  define SPRITESTUDIO_CORE_EXPORT Q_DECL_IMPORT
#endif

#endif // SPRITESTUDIOCORE_EXPORT_H
